export enum EstadoPagos {
  PENDIENTE = 'PENDIENTE',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  EN_PROCESO = 'EN_PROCESO',
  CANCELADO = 'CANCELADO',
  AUTORIZADO = 'AUTORIZADO',
  EN_MEDIACION = 'EN_MEDIACION',
  REEMBOLSADO = 'REEMBOLSADO',
  CONTRA_CARGO = 'CONTRA_CARGO'

}